# Generated by Django 4.2.1 on 2023-05-12 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=6)),
                ('machine', models.CharField(max_length=20)),
                ('dateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proactive', models.CharField(max_length=10)),
                ('repor', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting', to='django_app_one.breakdown')),
            ],
        ),
    ]
