# Generated by Django 4.2.1 on 2023-05-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_one', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporting',
            name='breakdown',
        ),
        migrations.AddField(
            model_name='reporting',
            name='proactive',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporting',
            name='proactive_remark',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
