# Generated by Django 4.2.1 on 2023-05-14 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_one', '0002_remove_reporting_breakdown_reporting_proactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reporting', to='django_app_one.reporting'),
            preserve_default=False,
        ),
    ]
