# Generated by Django 4.2.1 on 2023-05-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_one', '0005_breakdown_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakdown',
            name='report',
        ),
    ]
