# Generated by Django 4.2.1 on 2023-05-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_one', '0006_remove_breakdown_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='date',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
