# Generated by Django 4.2.1 on 2023-05-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_one', '0007_breakdown_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakdown',
            name='date',
        ),
    ]
