# Generated by Django 4.2.1 on 2023-05-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_one', '0009_alter_breakdown_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
