# Generated by Django 4.2.1 on 2023-05-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_one', '0010_alter_breakdown_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
