# Generated by Django 4.2.1 on 2023-05-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_one', '0012_breakdown_report_alter_breakdown_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakdown',
            name='report',
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
